In [1]:
from ipynb.fs.full.flights_models_v3 import *

C:\Users\duart\AppData\Local\conda\conda\envs\testEnv\lib\site-packages\IPython\core\interactiveshell.py:3242: DtypeWarning: Columns (48,69,76,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [2]:
data.head()

,Month,DayofMonth,DayOfWeek,ArrDel15,CRSDepTimeHour,dummyOriginATL,dummyOriginORD,dummyOriginDFW,dummyOriginDEN,dummyOriginCLT,...,dummyDestATL,dummyDestORD,dummyDestDFW,dummyDestDEN,dummyDestCLT,dummyDestLAX,dummyDestIAH,dummyDestPHX,dummyDestLGA,dummyDestSFO
882,11,1,5,0.0,8,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
950,11,1,5,0.0,18,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2101,11,1,5,0.0,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2105,11,1,5,0.0,14,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2200,11,1,5,0.0,20,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [7]:
predict_delay("11", 'JFK', 'ATL')

0.9235433171198434

In [15]:
# date / time, probability 

def recommend(hour, origin, destination, threshold):
    
    a = []

    max_hour = hour + threshold
    min_hour = hour - threshold
    
    for x in np.arange(min_hour, max_hour + 1):
        prediction = predict_delay(str(x), origin, destination)
        probability = 1 - prediction
        a.append(probability)
    
    recommendations = pd.DataFrame({"Time": list(np.arange(min_hour, max_hour + 1)),
                                   "Probability of Delay": a})
        
    return recommendations

In [16]:
recommend(11, "JFK", "ATL", 2)

   Time  Probability of Delay
0     9              0.092145
1    10              0.118569
2    11              0.076457
3    12              0.073073
4    13              0.135744

In [ ]:
# Problems for the group

# Day of the week, month, etc.
# Hour (same problem as the day of the week?). If not, can we include minutes
# No variable for airline?


# Problems for me and mark

# Reccomender system that reccomends actual flights (time, airline, etc.)? So we build a web crawler? Or base it only on historical data - using the schedule of the historical data
# Implement the airline