In [1]:
from pickle import *

model = load(open("flights.pickle.dat", 'rb'))

//anaconda3/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator NearestNeighbors from version 0.22.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
//anaconda3/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.22.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

In [2]:
from flights_v7 import *

In [3]:
rec_data = data

In [4]:
rec_data.head()

,MONTH,DAY_OF_WEEK,CRS_DEP_TIME,CRS_ARR_TIME,ARR_DEL15,TIME,avg_tax_out,avg_tax_in,airline_delay,origin_CLT,origin_DEN,origin_DFW,origin_IAH,origin_LAX,origin_LGA,origin_ORD,origin_PHX,origin_SFO,dest_CLT,dest_DEN,dest_DFW,dest_IAH,dest_LAX,dest_LGA,dest_ORD,dest_PHX,dest_SFO,airline_9E,airline_AA,airline_AS,airline_DL,airline_EV,airline_F9,airline_MQ,airline_NK,airline_OH,airline_OO,airline_UA,airline_YV,airline_YX
2079,1,5,600,745,0,5,21.931499,31.592411,67.189227,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2080,1,5,825,1005,0,7,21.931499,31.592411,67.189227,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2081,1,5,1055,1235,0,9,21.931499,31.592411,67.189227,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2082,1,5,1815,1955,0,17,21.931499,31.592411,67.189227,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2083,1,5,1300,1435,0,12,21.931499,31.592411,67.189227,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
# revised recommender function - works with arrival time

def recommend(arrival_time, origin, destination, airline = None, threshold = 2, rec_data = rec_data):
    
    # Transform arrival_time into an integer and military format
    
    hour = arrival_time[11:13]
    minutes = arrival_time[14:] 
    latest_time = int(hour + minutes)
    
    
    # Search for appropiate flights
    
    rec_data = rec_data[rec_data["CRS_ARR_TIME"] < latest_time]
        
    
    # Parse month and day of the week (why only monday and sunday)
    
    from datetime import datetime
    
    try:
        arrival_time_parsed = datetime.strptime(arrival_time, '%d/%m/%Y %H:%M')
    except ValueError as e:
        return 'Error parsing date/time - {}'.format(e)

    day_of_week = arrival_time_parsed.isoweekday()
    month = arrival_time_parsed.month
   
 
    # Create day of the week and month dictionaries 
    # day_dic = {1: "Monday", 7: "Sunday"}
    # month_dic = {1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 5: "May", 6: "Jun", 7: "Jul", 8: "Aug", 9: "Sep", 10: "Oct", 11: "Nov"}
  


 # Filtering ---
 
    # Filter the appropiate day and Month
    
    rec_data = rec_data[rec_data["DAY_OF_WEEK"] == day_of_week]
    rec_data = rec_data[rec_data["MONTH"] == month]


    # Filter out the airlines
    
    airlines = ['9E','AA', 'AS', 'DL', 'EV', 'F9', 'MQ', 'NK', 'OH', 'OO', 'UA','WN', 'YV', 'YX']
    
    if airline in airlines:
        rec_data = rec_data[rec_data["airline_" + airline] == 1]   
    
    # Filter out the destination and origin
    
    rec_data = rec_data[rec_data["origin_" + origin] == 1]
 
    rec_data = rec_data[rec_data["dest_" + destination] == 1]    
# --------------- 

    # Apply threshold for earliest arrival time
    
    earliest_time = latest_time - (threshold * 100)
    
    rec_data = rec_data[rec_data["CRS_ARR_TIME"] > earliest_time]  
  
    # Prepare Data for Input



    return rec_data

In [30]:
recommend("18/11/2020 20:30", "LAX", "SFO", threshold = 2)

,MONTH,DAY_OF_WEEK,CRS_DEP_TIME,CRS_ARR_TIME,ARR_DEL15,TIME,avg_tax_out,avg_tax_in,airline_delay,origin_CLT,origin_DEN,origin_DFW,origin_IAH,origin_LAX,origin_LGA,origin_ORD,origin_PHX,origin_SFO,dest_CLT,dest_DEN,dest_DFW,dest_IAH,dest_LAX,dest_LGA,dest_ORD,dest_PHX,dest_SFO,airline_9E,airline_AA,airline_AS,airline_DL,airline_EV,airline_F9,airline_MQ,airline_NK,airline_OH,airline_OO,airline_UA,airline_YV,airline_YX
6233849,11,3,1730,1901,0,16,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6233854,11,3,1830,2001,1,17,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6237974,11,3,1725,1848,0,16,40.335316,50.736059,53.334291,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
6275479,11,3,1830,1957,0,17,61.662007,39.913953,32.509768,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
6282280,11,3,1830,1957,0,17,61.662007,39.913953,32.509768,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
6438058,11,3,1830,1957,0,17,61.662007,39.913953,32.509768,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
6454836,11,3,1730,1901,0,16,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6454841,11,3,1830,2001,0,17,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6458294,11,3,1730,1901,0,16,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6458300,11,3,1830,2001,0,17,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6574489,11,3,1847,2017,0,17,41.587586,21.800062,58.817396,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
6574495,11,3,1847,2017,0,17,41.587586,21.800062,58.817396,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
6574501,11,3,1847,2017,0,17,41.587586,21.800062,58.817396,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
6699325,11,3,1730,1901,0,16,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6699331,11,3,1830,2001,0,17,93.405705,15.967721,38.456638,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
6737797,11,3,1725,1850,0,16,40.335316,50.736059,53.334291,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
6750865,11,3,1830,1957,0,17,61.662007,39.913953,32.509768,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0

In [19]:
# initial recommender function - works with departure time

def recommend(departure_time, origin, destination, airline = None, threshold = 2):
        """
        departure_time: dayofmonth/month/year hh:mm, str
        origin: three letter code for origin airport, str
        destination: three letter code for destination airport, str
        airline: two letter code for airline, str
        threshold: time interval the customer wants the flight recommendations, int
        """
                
        airlines = ['9E','AA', 'AS', 'DL', 'EV', 'F9','MQ', 'NK', 'OH', 'OO', 'UA','WN', 'YV', 'YX']
        
        a = []
        
        # define time intervals according to the threshold define by the customer

        max_hour = int(departure_time[11:13]) + threshold
        min_hour = int(departure_time[11:13]) - threshold

        recommendations = pd.DataFrame(columns = ["Date", "Time", "Airline", "Origin", "Destination", "Probability of Delay"])
            
        for x in np.arange(min_hour, max_hour + 1):
            
            # if the customer does not enter an airline, we will show results of all airlines
            
            if airline == None:
                
                # loop for all the airlines
                
                for b in airlines:
                    prediction = predict_delay(departure_time[:11] + str(x) + departure_time[13:], b, origin, destination)
                    probability = 1 - prediction
                
                    #append row to the dataframe
                    
                    to_append = [departure_time[:10], str(x) + departure_time[13:], b, origin, destination, probability]
                    series = pd.Series(to_append, index = recommendations.columns)
                    recommendations = recommendations.append(series, ignore_index = True)
                    
            # if the customer does enter an airline, we will only show results of that airline
            
            else:
                prediction = predict_delay(departure_time[:11] + str(x) + departure_time[13:], airline, origin, destination)
                probability = 1 - prediction
                
                #append row to the dataframe
                
                to_append = [departure_time[:10], str(x) + departure_time[13:], airline, origin, destination, probability]
                series = pd.Series(to_append, index = recommendations.columns)
                recommendations = recommendations.append(series, ignore_index = True)
        
        recommendations.sort_values(by = "Probability of Delay", ascending = True, inplace = True)
        recommendations['Probability of Delay'] = pd.Series(["{0:.2f}%".format(val * 100) for val in recommendations['Probability of Delay']], index = recommendations.index)
        
        return recommendations.head(10)